spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: boardm1
    password: 1111

server:
  port: 8084
